name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout commit
      uses: actions/checkout@v3
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm i
      # run: npm ci
    - name: Cache deps
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Linting typescript
      run: npm run lint:ts
    - name: Linting css
      run: npm run lint:scss

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Cache deps
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/checkout@v3
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm i
    - name: unit testing
      run: npm run test:unit

storybook:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [18.x]
  needs: [linting, unit-test]
  steps:
  - name: Cache deps
    uses: actions/cache@v3
    with:
      path: ~/.npm
      key: node-modules-${{ hashFiles('**/package-lock.json') }}
  - uses: actions/checkout@v3
  - name: Starting Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
  - name: install modules
    run: npm i
  - name: build storybook
    # - name: build production project
    #   run: npm run build:prod
    run: npm run storybook:build
  - name: screenshot testing
    run: npm run test:ui:ci
